{% set name = "azure-kusto-data" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-kusto-data-{{ version }}.tar.gz
  sha256: e6af9c3d573c224f75ab41c13b7d5948746b132861711781a371b86092c2cc29

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - python-dateutil >=2.8.0
    - requests >=2.13.0
    - azure-identity >=1.5.0,<2
    - msal >=1.9.0,<2
    - ijson >=3.1,<4.dev0
    - azure-core >=1.11.0,<2

test:
  imports:
    - azure.kusto
    - azure.kusto.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-kusto-python
  summary: Kusto Data Client
  description: |
    Kusto Python Client Library provides the capability to query Kusto clusters
    using Python. It is Python 3.x compatible and supports all data types
    through familiar Python DB API interface.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/Azure/azure-kusto-python
  dev_url: https://github.com/Azure/azure-kusto-python

extra:
  recipe-maintainers:
    - xylar
