{% set name = "azure-kusto-data" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1d5e04d273376330b58d6d11b055aeadda748cd1ecee1117fdc1b8329e76cb75

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - uv-build >=0.8.9,<0.9.0
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.9.0
    - requests >=2.32.4
    - azure-identity >=1.24.0,<2
    - msal >=1.34.0b1,<2
    - ijson >=3.4.0,<3.5.dev0
    - azure-core >=1.35.0,<2

test:
  imports:
    - azure.kusto
    - azure.kusto.data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-kusto-python
  summary: Kusto Data Client
  description: |
    Kusto Python Client Library provides the capability to query Kusto clusters
    using Python. It is Python 3.x compatible and supports all data types
    through familiar Python DB API interface.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/Azure/azure-kusto-python
  dev_url: https://github.com/Azure/azure-kusto-python

extra:
  recipe-maintainers:
    - xylar
