{% set name = "azure-kusto-data" %}
{% set version = "4.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure-kusto-data-{{ version }}.tar.gz
  sha256: 6875e50ce9f22be585ee6c92e92a33b52af20ebde6cd476130d7b9eca21371dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.8.0
    - requests >=2.13.0
    - azure-identity >=1.5.0,<2
    - msal >=1.9.0,<2
    - ijson >=3.1,<4.dev0
    - azure-core >=1.11.0,<2

test:
  imports:
    - azure.kusto
    - azure.kusto.data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-kusto-python
  summary: Kusto Data Client
  description: |
    Kusto Python Client Library provides the capability to query Kusto clusters
    using Python. It is Python 3.x compatible and supports all data types
    through familiar Python DB API interface.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/Azure/azure-kusto-python
  dev_url: https://github.com/Azure/azure-kusto-python

extra:
  recipe-maintainers:
    - xylar
